### ISSUE TITLE
迁移 Null safety

### ISSUE THREAD

**Issue by onerain88** [leancloud/Storage-SDK-Flutter#112]
## 介绍

Flutter 2 正式版已发布，但之前由于 SDK [依赖问题](https://dart.cn/null-safety/migration-guide)，导致无法迁移。
目前大部分依赖库都已支持，SDK 开始了迁移工作，见分支 [flutter2](https://github.com/onerain88/Storage-SDK-Flutter/tree/flutter2)。
SDK 还在迭代开发中，但大部分测试已通过。如果有在接入过程中遇到问题，请在此 issue 下反馈，我会及时响应的。

## 相关 issue

https://github.com/leancloud/Storage-SDK-Flutter/issues/106
https://github.com/leancloud/Storage-SDK-Flutter/issues/105

## 引用方式

开发者可先用 git 方式引入（待测试成熟后再发布至 pub），在 pubspec.yaml 中，调整 sdk 版本为 >=2.12.0，并输入下面的 github 地址
```yaml
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  leancloud_storage:
    git:
      url: https://github.com/leancloud/Storage-SDK-Flutter.git
      ref: flutter2
```

## 备注

目前依赖库 [dio_http_cache](https://github.com/hurshi/dio-http-cache) 看来正在适配 Null safety，所以是通过 git 方式引入的。
