### ISSUE TITLE
DioError [DioErrorType.RESPONSE]: Http status error [400]

### ISSUE THREAD

**Issue by chessl** [leancloud/Storage-SDK-Flutter#61]
Flutter version: 1.17.0
SDK version: 0.2.8

It used to work fine but I somehow bumped into this error and all tests started failing. All the uris in the error message are accessible from browser and terminal.

code snippet:
```
setUp(() {
    LeanCloud.initialize(Constants.appId, Constants.appKey, queryCache: LCQueryCache());
    LCLogger.setLevel(LCLogger.DebugLevel);
    userDataRepository = UserDataRepository();
  });

  test('ping', () async {
    LCObject object = LCObject('TestObject');
    object['words'] = 'Hello world!';
    await object.save();
  });
```

error message:
```
*** Request ***
uri: https://app-router.com/2/route?appId=4Fayf9FEEn3t0HSacoLU68Ue-MdYXbMMI
method: GET
responseType: ResponseType.json
followRedirects: true
connectTimeout: 0
receiveTimeout: 0
extra: {}
headers:
 content-type: application/json; charset=utf-8
data:
null

*** DioError ***:
uri: https://app-router.com/2/route?appId=4Fayf9FEEn3t0HSacoLU68Ue-MdYXbMMI
DioError [DioErrorType.RESPONSE]: Http status error [400]
uri: https://app-router.com/2/route?appId=4Fayf9FEEn3t0HSacoLU68Ue-MdYXbMMI
statusCode: 400
headers:
Response Text:



*** Request ***
uri: https://4fayf9fe.api.lncldglobal.com/1.1/classes/TestObject
method: POST
responseType: ResponseType.json
followRedirects: true
connectTimeout: 0
receiveTimeout: 0
extra: {}
headers:
 x-lc-id: 4Fayf9FEEn3t0HSacoLU68Ue-MdYXbMMI
 content-type: application/json; charset=utf-8
 user-agent: LeanCloud-Flutter-SDK/0.2.8
 x-lc-sign: hidden
data:
{words: Hello world!}

*** DioError ***:
uri: https://4fayf9fe.api.lncldglobal.com/1.1/classes/TestObject
DioError [DioErrorType.RESPONSE]: Http status error [400]
uri: https://4fayf9fe.api.lncldglobal.com/1.1/classes/TestObject
statusCode: 400
headers:
Response Text:



ERROR: type 'String' is not a subtype of type 'int' of 'index'
package:leancloud_storage/internal/http/lc_http_client.dart 152:31  _LCHttpClient._handleError
package:leancloud_storage/internal/http/lc_http_client.dart 75:7    _LCHttpClient.post
```

**Comment by onerain88** [comment]
When the error occurs again, please open the [link](http://ping.leanapp.cn/) in your browser.
Save the results and paste them here, thank you.

**Comment by chessl** [comment]
Problem solved, the error was caused by this line `WidgetsFlutterBinding.ensureInitialized();` in the test main function. However, the reason why I had this line is because I had this test case
```
test('should return all users', () async {
    final userQuery = LCUser.getQuery();
    final users = await userQuery.find();
    print(users);
});
```
and it outputted the following error:
```
*** Request ***
uri: https://4fayf9fe.api.lncldglobal.com/1.1/classes/_User?skip=0&limit=30
method: GET
responseType: ResponseType.json
followRedirects: true
connectTimeout: 0
receiveTimeout: 0
extra: {dio_cache_try_cache: true, dio_cache_max_age: 168:00:00.000000, dio_cache_force_refresh: true}
headers:
 x-lc-id: 4Fayf9FEEn3t0HSacoLU68Ue-MdYXbMMI
 content-type: application/json; charset=utf-8
 user-agent: LeanCloud-Flutter-SDK/0.2.8
 x-lc-sign: hidden
data:
null

*** DioError ***:
uri: https://4fayf9fe.api.lncldglobal.com/1.1/classes/_User?skip=0&limit=30
DioError [DioErrorType.DEFAULT]: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
#0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:76:7)
#1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:89:4)
#2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
#3      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:146:35)
#4      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
#5      invokeMethod (package:sqflite/src/sqflite_impl.dart:17:13)
#6      SqfliteDatabaseFactoryImpl.invokeMethod (package:sqflite/src/factory_impl.dart:31:7)
#7      SqfliteDatabaseFactoryMixin.safeInvokeMethod.<anonymous closure> (package:sqflite_common/src/factory_mixin.dart:25:35)
#8      wrapDatabaseException (package:sqflite/src/exception_impl.dart:7:32)
#9      SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:27:7)
#10     SqfliteDatabaseFactoryMixin.safeInvokeMethod (package:sqflite_common/src/factory_mixin.dart:25:7)
#11     SqfliteDatabaseFactoryMixin.getDatabasesPath (package:sqflite_common/src/factory_mixin.dart:143:26)
#12     getDatabasesPath (package:sqflite/sqflite.dart:168:54)
#13     DiskCacheStore._database (package:dio_http_cache/src/core/store.dart:41:24)
#14     DiskCacheStore.getCacheObj (package:dio_http_cache/src/core/store.dart:120:20)
#15     CacheManager._pullFromCache (package:dio_http_cache/src/core/manager.dart:28:36)
<asynchronous suspension>
#16     CacheManager.pullFromCacheBeforeMaxStale (package:dio_http_cache/src/core/manager.dart:63:18)
#17     DioCacheManager._pullFromCacheBeforeMaxStale (package:dio_http_cache/src/manager_dio.dart:102:22)
#18     DioCacheManager._onError (package:dio_http_cache/src/manager_dio.dart:64:41)
#19     InterceptorsWrapper.onError (package:dio/src/interceptor.dart:125:22)
#20     DioMixin._request._errorInterceptorWrapper.<anonymous closure> (package:dio/src/dio.dart:867:40)
#21     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
#22     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#23     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
#24     _rootRunUnary (dart:async/zone.dart:1192:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#26     _FutureListener.handleError (dart:async/future_impl.dart:159:20)
#27     Future._propagateToListeners.handleError (dart:async/future_impl.dart:694:47)
#28     Future._propagateToListeners (dart:async/future_impl.dart:715:24)
#29     Future._completeError (dart:async/future_impl.dart:534:5)
#30     _SyncCompleter._completeError (dart:async/future_impl.dart:58:12)
#31     _Completer.completeError (dart:async/future_impl.dart:30:5)
#32     Future.any.<anonymous closure> (dart:async/future.dart:464:45)
#33     StackZoneSpecification._registerBinaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:141:26)
#34     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#35     StackZoneSpecification._registerBinaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:141:14)
#36     _rootRunBinary (dart:async/zone.dart:1204:38)
#37     _CustomZone.runBinary (dart:async/zone.dart:1093:19)
#38     _FutureListener.handleError (dart:async/future_impl.dart:155:20)
#39     Future._propagateToListeners.handleError (dart:async/future_impl.dart:694:47)
#40     Future._propagateToListeners (dart:async/future_impl.dart:715:24)
#41     Future._completeError (dart:async/future_impl.dart:534:5)
#42     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:43:15)
#43     DioMixin._dispatchRequest (package:dio/src/dio.dart)
<asynchronous suspension>
#44     DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:849:37)
#45     DioMixin.checkIfNeedEnqueue (package:dio/src/dio.dart:1117:22)
#46     DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:846:22)
#47     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#48     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#49     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#50     _rootRun (dart:async/zone.dart:1180:38)
#51     _CustomZone.run (dart:async/zone.dart:1077:19)
#52     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#53     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#54     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#55     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#56     _rootRun (dart:async/zone.dart:1184:13)
#57     _CustomZone.run (dart:async/zone.dart:1077:19)
#58     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1003:23)
#59     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#60     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#61     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#62     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
package:leancloud_storage/internal/http/lc_http_client.dart 147:7  _LCHttpClient._handleError
package:leancloud_storage/internal/http/lc_http_client.dart 60:7   _LCHttpClient.get
```
After several tests this error only turned out when querying all users, is there anyway to go around with this?
